---
- name: ansible
  box: centos/7
  cpus: 1
  memory: 512
  shells:
    - path: restart_sshd.sh
  private_networks:  #Internal only interfaces
    - ip: 10.0.0.11
      desc: 01-to-02
- name: gitlab
  box: centos/7
  cpus: 1
  memory: 512
  shells:
    - path: restart_sshd.sh
  private_networks:  #Internal only interfaces
    - ip: 10.0.0.12
      desc: 02-to-03
- name: jenkins
  box: centos/7
  cpus: 1
  memory: 512
  shells:
    - path: restart_sshd.sh
  private_networks:  #Internal only interfaces
    - ip: 10.0.0.13
      desc: 'Network to Advertise'
- name: nginx
  box: centos/7
  cpus: 1
  memory: 512
  shells:
    - path: restart_sshd.sh
  private_networks:  #Internal only interfaces
    - ip: 10.0.0.21
      desc: 01-to-04
- name: php1
  box: centos/7
  cpus: 1
  memory: 512
  shells:
    - path: restart_sshd.sh
  private_networks:  #Internal only interfaces
    - ip: 10.0.0.31
      desc: 01-to-04
- name: php2
  box: centos/7
  cpus: 1
  memory: 512
  shells:
    - path: restart_sshd.sh
  private_networks:  #Internal only interfaces
    - ip: 10.0.0.32
      desc: 01-to-04
- name: mysql1
  box: centos/7
  cpus: 1
  memory: 512
  shells:
    - path: restart_sshd.sh
  private_networks:  #Internal only interfaces
    - ip: 10.0.0.41
      desc: 01-to-04
- name: mysql2
  box: centos/7
  cpus: 1
  memory: 512
  shells:
    - path: restart_sshd.sh
  private_networks:  #Internal only interfaces
    - ip: 10.0.0.42
      desc: 01-to-04
- name: mysql3
  box: centos/7
  cpus: 1
  memory: 512
  shells:
    - path: restart_sshd.sh
  private_networks:  #Internal only interfaces
    - ip: 10.0.0.43
      desc: 01-to-04

