---
- name: r1
  box: ubuntu/trusty64
  mem: 512
  cpus: 1
  priv_ip_1: 192.168.250.101  #HostOnly interface
  priv_ips:  #Internal only interfaces
    - ip: 192.168.12.11
      desc: 01-to-02
    - ip: 192.168.14.11
      desc: 01-to-04
    - ip: 192.168.31.11
      desc: 03-to-01
    - ip: 1.1.1.10
      desc: 'Network to Advertise'
- name: r2
  box: ubuntu/trusty64
  mem: 512
  cpus: 1
  priv_ip_1: 192.168.250.102  #HostOnly interface
  priv_ips:  #Internal only interfaces
    - ip: 192.168.23.12
      desc: 02-to-03
    - ip: 192.168.12.12
      desc: 01-to-02
    - ip: 2.2.2.10
      desc: 'Network to Advertise'
- name: r3
  box: ubuntu/trusty64
  mem: 512
  cpus: 1
  priv_ip_1: 192.168.250.103  #HostOnly interface
  priv_ips:  #Internal only interfaces
    - ip: 192.168.31.13
      desc: 03-to-01
    - ip: 192.168.23.13
      desc: 02-to-03
    - ip: 3.3.3.10
      desc: 'Network to Advertise'
- name: r4
  box: ubuntu/trusty64
  mem: 512
  cpus: 1
  priv_ip_1: 192.168.250.104  #HostOnly interface
  priv_ips:  #Internal only interfaces
    - ip: 192.168.14.14
      desc: 01-to-04
    - ip: 192.168.31.14
      desc: 03-to-01
    - ip: 192.168.41.14
      desc: utopia
    - ip: 4.4.4.10
      desc: 'Network to Advertise'
